import { db } from './index';
import { menuItems } from './schema';
import { sql } from 'drizzle-orm';

export const initialMenuItems = [
  // VEG BURGER
  {
    name: 'Veg Burger',
    description: 'Crispy seasoned vegetable patty topped with fresh lettuce, onions, and signature camp sauce.',
    price: 70,
    category: 'Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1585238342024-78d387f4a707?auto=format&fit=crop&w=800&q=80',
    isVegetarian: true,
    isAvailable: true,
    sortOrder: 1,
  },
  {
    name: 'Veg Jumbo Burger',
    description: 'Double-decker crispy veg patties loaded with extra crunch, fresh veggies, and rich creamy mayo.',
    price: 110,
    category: 'Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?auto=format&fit=crop&w=800&q=80',
    isVegetarian: true,
    isAvailable: true,
    sortOrder: 2,
  },
  {
    name: 'Veg Tandoori Burger',
    description: 'Crispy vegetable patty infused with smoky tandoori spices and spicy tandoori mayonnaise.',
    price: 90,
    category: 'Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    isVegetarian: true,
    isAvailable: true,
    sortOrder: 3,
  },
  {
    name: 'Veg Peri Peri Burger',
    description: 'Golden spiced veg patty dusted with fiery African peri peri seasoning and tangy relish.',
    price: 80,
    category: 'Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80',
    isVegetarian: true,
    isAvailable: true,
    sortOrder: 4,
  },
  {
    name: 'Veg Cheese Burger',
    description: 'Classic spiced veg patty topped with a melt-in-mouth cheese slice, crunchy lettuce, and house sauce.',
    price: 90,
    category: 'Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?auto=format&fit=crop&w=800&q=80',
    isVegetarian: true,
    isAvailable: true,
    sortOrder: 5,
  },
  {
    name: 'Cheese Potato Burger',
    description: 'Herb-crusted spiced potato patty layered with cheddar cheese, crunchy onions, and herb mayo.',
    price: 90,
    category: 'Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=800&q=80',
    isVegetarian: true,
    isAvailable: true,
    sortOrder: 6,
  },
  {
    name: 'Paneer Burger',
    description: 'Thick golden-fried spiced cottage cheese slab with crisp lettuce and creamy herb dressing.',
    price: 90,
    category: 'Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?auto=format&fit=crop&w=800&q=80',
    isVegetarian: true,
    isAvailable: true,
    sortOrder: 7,
  },
  {
    name: 'Paneer Jumbo',
    description: 'Extra large paneer patty double-breaded for maximum crunch, topped with premium cheese and zesty sauce.',
    price: 130,
    category: 'Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?auto=format&fit=crop&w=800&q=80',
    isVegetarian: true,
    isAvailable: true,
    sortOrder: 8,
  },

  // CHICKEN BURGER
  {
    name: 'Chicken Tandoori Burger',
    description: 'Tender chicken patty marinated in rich tandoori spices, flame-grilled and topped with smoky sauce.',
    price: 130,
    category: 'Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?auto=format&fit=crop&w=800&q=80',
    isVegetarian: false,
    isAvailable: true,
    sortOrder: 9,
  },
  {
    name: 'Chicken Ham Burger',
    description: 'Juicy chicken patty topped with savory sliced chicken ham, melted cheese, and creamy dressing.',
    price: 120,
    category: 'Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?auto=format&fit=crop&w=800&q=80',
    isVegetarian: false,
    isAvailable: true,
    sortOrder: 10,
  },
  {
    name: 'Chicken Salami Burger',
    description: 'Succulent chicken patty paired with seasoned chicken salami slices and spicy camp sauce.',
    price: 120,
    category: 'Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=800&q=80',
    isVegetarian: false,
    isAvailable: true,
    sortOrder: 11,
  },
  {
    name: 'Chicken Tandoori Jumbo Burger',
    description: 'Giant double chicken patty smothered in smoky tandoori twist sauce, crunchy slaw, and melted cheese.',
    price: 150,
    category: 'Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80',
    isVegetarian: false,
    isAvailable: true,
    sortOrder: 12,
  },
  {
    name: 'Chicken Cheese Burger',
    description: 'Crispy golden chicken patty topped with molten American cheddar cheese, pickles, and special sauce.',
    price: 120,
    category: 'Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1619881589139-2c0eb1d2793e?auto=format&fit=crop&w=800&q=80',
    isVegetarian: false,
    isAvailable: true,
    sortOrder: 13,
  },
  {
    name: 'Chicken Medium Burger',
    description: 'Classic crispy fried chicken patty with shredded iceberg lettuce and tangy mayonnaise on a toasted bun.',
    price: 100,
    category: 'Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1608767221051-2b9d18f35a2f?auto=format&fit=crop&w=800&q=80',
    isVegetarian: false,
    isAvailable: true,
    sortOrder: 14,
  },
  {
    name: 'Chicken Jumbo Burger',
    description: 'Hefty oversized crispy chicken patty with double layer of sauces, pickles, and crisp onions.',
    price: 130,
    category: 'Burgers',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    isVegetarian: false,
    isAvailable: true,
    sortOrder: 15,
  },

  // COMBOS
  {
    name: 'Chicken Medium Combo',
    description: 'Chicken Medium Burger served with a portion of crispy salted fries and a chilled beverage.',
    price: 170,
    category: 'Combos',
    imageUrl: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=800&q=80',
    isVegetarian: false,
    isAvailable: true,
    sortOrder: 16,
  },
  {
    name: 'Chicken Jumbo Combo',
    description: 'Massive Chicken Jumbo Burger accompanied by golden fries and a refreshing cold drink.',
    price: 200,
    category: 'Combos',
    imageUrl: 'https://images.unsplash.com/photo-1551782450-17144efb9c50?auto=format&fit=crop&w=800&q=80',
    isVegetarian: false,
    isAvailable: true,
    sortOrder: 17,
  },
  {
    name: 'Veg Combo',
    description: 'Classic Veg Burger paired with piping hot salted fries and a chilled soft drink.',
    price: 140,
    category: 'Combos',
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80',
    isVegetarian: true,
    isAvailable: true,
    sortOrder: 18,
  },
  {
    name: 'Veg Jumbo Combo',
    description: 'Hearty Veg Jumbo Burger served with golden crispy fries and a chilled beverage.',
    price: 170,
    category: 'Combos',
    imageUrl: 'https://images.unsplash.com/photo-1610614819513-58e34989848b?auto=format&fit=crop&w=800&q=80',
    isVegetarian: true,
    isAvailable: true,
    sortOrder: 19,
  },

  // BEVERAGES / SIDES
  {
    name: 'Salted Fries',
    description: 'Golden crispy potato fries lightly sprinkled with sea salt, served hot and fresh.',
    price: 60,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=800&q=80',
    isVegetarian: true,
    isAvailable: true,
    sortOrder: 20,
  },
  {
    name: 'Pari Peri Fries',
    description: 'Crispy golden fries tossed in our signature zesty African peri peri spice blend.',
    price: 80,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&w=800&q=80',
    isVegetarian: true,
    isAvailable: true,
    sortOrder: 21,
  },
  {
    name: 'Cheese Fries',
    description: 'Hot crunchy fries smothered in warm, velvety melted cheese sauce.',
    price: 100,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1586816001966-79b736744398?auto=format&fit=crop&w=800&q=80',
    isVegetarian: true,
    isAvailable: true,
    sortOrder: 22,
  },
  {
    name: 'Extra Mayo.',
    description: 'Extra dip of our rich, velvety house mayonnaise.',
    price: 20,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
    isVegetarian: true,
    isAvailable: true,
    sortOrder: 23,
  },
  {
    name: 'Extra Cheese',
    description: 'An extra slice of rich, melted cheddar cheese to elevate your burger.',
    price: 20,
    category: 'Sides',
    imageUrl: 'https://images.unsplash.com/photo-1624806992066-5ffcf7ca186b?auto=format&fit=crop&w=800&q=80',
    isVegetarian: true,
    isAvailable: true,
    sortOrder: 24,
  },
];

export async function seedMenu() {
  const existingCount = await db.select({ count: sql`count(*)` }).from(menuItems);
  if (Number(existingCount[0].count) === 0) {
    console.log('Seeding initial menu items...');
    await db.insert(menuItems).values(initialMenuItems);
    console.log('Menu items seeded successfully.');
  }
}
